### ISSUE TITLE
D-031 add food types in settings

### ISSUE THREAD

**Issue by ghinta** [sw21-tug/Team_05#65]
**As a**
cat owner
**I want to**
add and remove food types on the food page
**so that**
the food I feed my cats is shown on the cat cards.

* [ ] add a new button to the user settings
* [ ] create new food type screen
* [ ] create a list of the users food type
* [ ] possibility to delete this food type
* [ ] required fields
    name
    %raw protein
    %raw fat
    %crude ash
    %raw fiber
    %water

**Comment by cpiber** [comment]
http://www.kretakatzen.de/Ernaehrung/Naehrwert/Naehrwert-Berechnung.htm
