### ISSUE TITLE
D-032 calculate and show food recommendation

### ISSUE THREAD

**Issue by ghinta** [sw21-tug/Team_05#66]
**As a**
cat owner
**I want to**
the app to calculate how much cal/g my entered food types have
**so that**
the app can show the daily food amount correctly on the expanded cat card

* [x] calculate how much cal/g the entered food types have
* [x] show the daily food recommendation on the cat card

http://www.kretakatzen.de/Ernaehrung/Naehrwert/Naehrwert-Berechnung.htm

**Comment by cpiber** [comment]
Also consider setting the values by default to `null` and returning an empty string in that case to avoid pre-filling with `0.0`
