### ISSUE TITLE
D-035 remove warnings from project

### ISSUE THREAD

**Issue by ghinta** [sw21-tug/Team_05#73]
* [x] remove the warnings
* [x] add support for API 26
* [x] add test runner

**Comment by cpiber** [comment]
I also noticed a few little things, maybe we can put this here as well:

- On the home screen, if the user has not entered any cats, it's completely empty. A better option might be to have a little text telling them what they'd usually see here and how to get started
- In the cat accordion, currently the foods directly follow the cat's data, no spacing. I think a separation would be helpful. Also it's not really clear what the food list is saying. To avoid confusion, a little sentence telling the user that the calories can be consumed with *one of* the listed quantities would be nice
- On the AddCat screen, the size and weight values are pre-filled with 0.0. That's neither a sensible default nor nice to enter new values (have to delete it manually). We could allow those values to be nullable again and set an empty string if they are. To avoid problems, we could then simply save 0 in the database if it's null on save (might be a sensible idea for other properties as well?). Having something pre-filled in also hides the placeholder text with the units. In general, I think it would be helpful to have the units always displayed next to the input field
- On the settings screen, the languages are always displayed in English. The rationale was that an English person might not be able to switch back after accidentally switching to Chinese. But that same thinking holds true for Chinese people. So maybe a better option would be to display the name in that language, but put the short name in the current language in brackets there as well
