### ISSUE TITLE
D-030 convert calories to food

### ISSUE THREAD

**Issue by CommodoreEU** [sw21-tug/Team_05#9]
# user story

**As a**
cat owner
**I want to**
check how much food the calories are
**so that**
I know how much to actually feed my cat

# acceptance criteria

- [ ] at expanded cat card have list of cat foods with name on the left and daily grams/ounces on the right
- [ ] will be dynamic in the future, so different food types can be added and removed
- [ ] will have a button in the future where user can enter already fed grams/ounces

**Comment by cpiber** [comment]
http://www.kretakatzen.de/Ernaehrung/Naehrwert/Naehrwert-Berechnung.htm
